name: Build Sextb

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build Plugin
        run: ./gradlew :Sextb:make

      - name: Prepare builds folder
        run: |
          mkdir -p builds
          find . -name "*.cs3" -exec cp {} builds/ \;

      - name: Generate plugins.json
        run: |
          echo '[
            {
              "name": "Sextb",
              "url": "https://raw.githubusercontent.com/mcvo1705/CXXX/master/builds/Sextb.cs3",
              "version": 1
            }
          ]' > builds/plugins.json

      - name: Commit builds
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add builds

          git commit -m "Update builds" || echo "No changes"

          git push
